# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-07 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0187_auto_20191007_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultcondition',
            old_name='condition',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='defaultcondition',
            name='return_type',
        ),
        migrations.AddField(
            model_name='defaultcondition',
            name='standard_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.ApplicationStandardCondition'),
        ),
    ]
