# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-06 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0188_auto_20191007_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationselectedactivity',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_officer_finalisation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationselectedactivity',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_officer', 'With Officer'), ('with_assessor', 'With Assessor'), ('with_officer_conditions', 'With Officer-Conditions'), ('with_officer_finalisation', 'With Approver'), ('awaiting_licence_fee_payment', 'Awaiting Licence Fee Payment'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('discarded', 'Discarded')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
    ]
