# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-11 07:06
# WildlifeCompliance: UPDATE allocation of assigned officer to licence activity.
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0189_auto_20191106_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='assigned_officer',
        ),
        migrations.AddField(
            model_name='applicationselectedactivity',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_officer', to=settings.AUTH_USER_MODEL),
        ),
    ]
