# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-19 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0190_auto_20191111_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='licence_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.LicenceDocument'),
        ),
    ]
