# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-20 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0191_application_licence_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationselectedactivity',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8),
        ),
    ]
