# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-27 03:46
# creation of Invoice Line details to persist detail amounts per activity.
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0192_applicationselectedactivity_application_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default='0', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationInvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default='0', max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='activityinvoice',
            name='invoice_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applicationinvoice',
            name='invoice_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applicationinvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_activity_lines', to='wildlifecompliance.ApplicationInvoice'),
        ),
        migrations.AddField(
            model_name='applicationinvoiceline',
            name='licence_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.LicenceActivity'),
        ),
        migrations.AddField(
            model_name='activityinvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_activity_lines', to='wildlifecompliance.ActivityInvoice'),
        ),
        migrations.AddField(
            model_name='activityinvoiceline',
            name='licence_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.LicenceActivity'),
        ),
    ]
