# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-15 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0193_auto_20191227_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationselectedactivity',
            options={'verbose_name': 'Application selected activity', 'verbose_name_plural': 'Application selected activities'},
        ),
    ]
