# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-18 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0302_weaklinks_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callemail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('open_followup', 'Open (follow-up)'), ('open_inspection', 'Open (Inspection)'), ('open_case', 'Open (Case)'), ('closed', 'Closed'), ('pending_closure', 'Pending Closure')], default='draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('await_endorsement', 'Awaiting Endorsement'), ('discarded', 'Discarded'), ('closed', 'Closed'), ('pending_closure', 'Pending Closure')], default='open', max_length=100),
        ),
    ]
