# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-19 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0303_auto_20190918_1525'),
        ('wildlifecompliance', '0303_auto_20190918_0951'),
    ]

    operations = [
    ]
