# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-19 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0303_auto_20190918_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryDocumentCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='temporarydocument',
            name='temp_documents',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='wildlifecompliance.TemporaryDocumentCollection'),
            preserve_default=False,
        ),
    ]
