# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-19 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0304_auto_20190919_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporarydocument',
            old_name='temp_documents',
            new_name='temp_document_collection',
        ),
    ]
