# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-20 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0305_auto_20190919_1312'),
        ('wildlifecompliance', '0304_merge_20190919_1110'),
    ]

    operations = [
    ]
