# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-23 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0305_offenceuseraction'),
        ('wildlifecompliance', '0306_merge_20190920_1146'),
    ]

    operations = [
    ]
