# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-24 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0308_auto_20190923_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_location', to='wildlifecompliance.Location'),
        ),
    ]
