# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-07 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0309_inspection_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offence',
            name='status',
            field=models.CharField(choices=[(b'draft', b'Draft'), (b'open', b'Open'), (b'pending_closure', b'Pending Closure'), (b'closed', b'Closed'), (b'discarded', b'Discarded')], default=b'open', max_length=40),
        ),
        migrations.AlterField(
            model_name='sanctionoutcome',
            name='offence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offence_sanction_outcomes', to='wildlifecompliance.Offence'),
        ),
        migrations.AlterField(
            model_name='sanctionoutcome',
            name='status',
            field=models.CharField(choices=[(b'draft', b'Draft'), (b'awaiting_endorsement', b'Awaiting Endorsement'), (b'awaiting_payment', b'Awaiting Payment'), (b'awaiting_review', b'Awaiting Review'), (b'awaiting_amendment', b'Awaiting Amendment'), (b'awaiting_remediation_actions', b'Awaiting Remediation Actions'), (b'declined', b'Declined'), (b'withdrawn', b'Withdrawn'), (b'closed', b'closed')], default=b'draft', max_length=40),
        ),
    ]
