# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-16 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0311_auto_20191011_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionoutcome',
            name='payment_status',
            field=models.CharField(blank=True, choices=[(b'paid', b'Paid'), (b'unpaid', b'Unpaid')], max_length=40),
        ),
    ]
