# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-17 03:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0312_sanctionoutcome_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offenceuseraction',
            name='who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
