# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-16 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0313_auto_20191016_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcase',
            name='allocated_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_case_allocated_group', to='wildlifecompliance.CompliancePermissionGroup'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_case_district', to='wildlifecompliance.RegionDistrict'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_case_region', to='wildlifecompliance.RegionDistrict'),
        ),
    ]
