# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-16 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0315_auto_20191016_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callemail',
            name='case_priority',
        ),
        migrations.DeleteModel(
            name='CasePriority',
        ),
    ]
