# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-16 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0316_auto_20191016_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcase',
            name='legal_case_priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.LegalCasePriority'),
        ),
    ]
