# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-22 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0315_infringementpenalty_infringementpenaltyinvoice'),
        ('wildlifecompliance', '0318_auto_20191021_1614'),
    ]

    operations = [
    ]
