# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-25 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0320_auto_20191024_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionregulation',
            name='amount',
        ),
    ]
