# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-30 06:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0023_communicationslogentry_log_type'),
        ('wildlifecompliance', '0322_auto_20191025_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCasePerson',
            fields=[
                ('emailuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_case_person', to='wildlifecompliance.LegalCase')),
            ],
            bases=('accounts.emailuser',),
        ),
        migrations.CreateModel(
            name='LegalCaseRunningSheetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_sheet_entry', to='wildlifecompliance.LegalCase')),
                ('person', models.ManyToManyField(related_name='running_sheet_entry_person', to='wildlifecompliance.LegalCasePerson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_sheet_entry_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
