# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-31 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0323_legalcaseperson_legalcaserunningsheetentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcaserunningsheetentry',
            name='row_num',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='legalcaserunningsheetentry',
            name='number',
        ),
        migrations.AlterUniqueTogether(
            name='legalcaserunningsheetentry',
            unique_together=set([('legal_case', 'row_num')]),
        ),
    ]
