# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-31 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0324_auto_20191031_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcaserunningsheetentry',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
