# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-01 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0325_legalcaserunningsheetentry_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcaserunningsheetentry',
            name='row_num',
            field=models.SmallIntegerField(),
        ),
    ]
