# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-31 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0326_auto_20191031_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionoutcome',
            name='due_date_auto_1st',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanctionoutcome',
            name='due_date_auto_2nd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanctionoutcome',
            name='due_date_extended_max',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanctionoutcome',
            name='due_date_manual_1st',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanctionoutcome',
            name='due_date_manual_2nd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanctionoutcome',
            name='penalty_amount_2nd',
            field=models.DecimalField(decimal_places=2, default=b'0.00', max_digits=8),
        ),
    ]
