# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-04 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0327_auto_20191031_1501'),
        ('wildlifecompliance', '0327_auto_20191101_1818'),
    ]

    operations = [
    ]
