# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-05 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0327_auto_20191031_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionregulation',
            name='issue_due_date_window',
            field=models.PositiveSmallIntegerField(blank=True, help_text=b'An infringement notice must be issued within Issue-due-date-window days from the date of the offence occurred.', null=True),
        ),
    ]
