# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-05 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0328_auto_20191105_1321'),
        ('wildlifecompliance', '0327_auto_20191101_1818'),
    ]

    operations = [
    ]
