# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-08 02:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0329_auto_20191107_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionOutcomeDueDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date_1st', models.DateField(blank=True, null=True)),
                ('due_date_2nd', models.DateField(blank=True, null=True)),
                ('reason_for_extension', models.TextField(blank=True)),
                ('extended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sanction_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.SanctionOutcome')),
            ],
            options={
                'verbose_name': 'CM_SanctionOutcomeDueDate',
                'verbose_name_plural': 'CM_SanctionOutcomeDueDates',
            },
        ),
    ]
