# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-06 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0329_merge_20191105_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcaserunningsheetentry',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
