# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-08 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0330_sanctionoutcomeduedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanctionoutcome',
            name='due_date_auto_1st',
        ),
        migrations.RemoveField(
            model_name='sanctionoutcome',
            name='due_date_auto_2nd',
        ),
        migrations.RemoveField(
            model_name='sanctionoutcome',
            name='due_date_manual_1st',
        ),
        migrations.RemoveField(
            model_name='sanctionoutcome',
            name='due_date_manual_2nd',
        ),
    ]
