# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-08 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0331_auto_20191108_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionoutcomeduedate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sanctionoutcomeduedate',
            name='sanction_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_dates', to='wildlifecompliance.SanctionOutcome'),
        ),
    ]
