# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-11 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0332_auto_20191108_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanctionoutcomeduedate',
            options={'ordering': ('created_at',), 'verbose_name': 'CM_SanctionOutcomeDueDate', 'verbose_name_plural': 'CM_SanctionOutcomeDueDates'},
        ),
    ]
