# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-18 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0333_auto_20191111_1206'),
        ('wildlifecompliance', '0330_auto_20191106_1014'),
    ]

    operations = [
    ]
