# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-21 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0334_merge_20191118_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcaserunningsheetentry',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
