# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-22 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0336_auto_20191121_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionoutcome',
            name='fer_case_number',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
