# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-22 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0336_auto_20191121_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalcaserunningsheetentry',
            name='date_created',
        ),
        migrations.AddField(
            model_name='legalcaserunningsheetentry',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
