# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-23 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0337_sanctionoutcome_fer_case_number'),
        ('wildlifecompliance', '0337_auto_20191122_1356'),
    ]

    operations = [
    ]
