# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-27 04:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0339_auto_20191126_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionoutcome',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanction_outcome_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sanctionoutcome',
            name='registration_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanction_outcome_registration_holder', to=settings.AUTH_USER_MODEL),
        ),
    ]
