# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-02 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0340_auto_20191127_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionoutcomeduedate',
            name='due_date_term_currently_applied',
            field=models.CharField(default=b'1st', max_length=3),
        ),
    ]
