# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-12 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0341_sanctionoutcomeduedate_due_date_term_currently_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnpaidInfringementFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CM_UnpaidInfringementFile',
                'verbose_name_plural': 'CM_UnpaidInfringementFiles',
            },
        ),
        migrations.AlterField(
            model_name='sanctionoutcome',
            name='status',
            field=models.CharField(choices=[(b'draft', b'Draft'), (b'awaiting_endorsement', b'Awaiting Endorsement'), (b'awaiting_payment', b'Awaiting Payment'), (b'with_dot', b'With Dep. of Transport'), (b'awaiting_issuance', b'Awaiting Issuance'), (b'awaiting_review', b'Awaiting Review'), (b'awaiting_issuance', b'Awaiting Issuance'), (b'awaiting_remediation_actions', b'Awaiting Remediation Actions'), (b'escalated_for_withdrawal', b'Escalated for Withdrawal'), (b'declined', b'Declined'), (b'overdue', b'Overdue'), (b'withdrawn', b'Withdrawn'), (b'closed', b'Closed')], default=b'draft', max_length=40),
        ),
    ]
