# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-13 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0342_auto_20191212_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionregulation',
            name='dotag_offence_code',
            field=models.CharField(blank=True, max_length=9, verbose_name=b'DotAG Offence Code'),
        ),
    ]
