# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-11 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0342_auto_20191211_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentartifact',
            name='_file',
        ),
        migrations.RemoveField(
            model_name='documentartifact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='documentartifact',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='physicalartifact',
            name='_file',
        ),
        migrations.RemoveField(
            model_name='physicalartifact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='physicalartifact',
            name='identifier',
        ),
        migrations.AddField(
            model_name='artifact',
            name='_file',
            field=models.FileField(max_length=255, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='artifact',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
