# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-16 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0343_sectionregulation_dotag_offence_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionoutcome',
            name='registration_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
