# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-17 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0344_sanctionoutcome_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotRequestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sanction_outcomes', models.ManyToManyField(related_name='dot_request_files', to='wildlifecompliance.SanctionOutcome')),
            ],
            options={
                'verbose_name': 'CM_DotReguestFile',
                'verbose_name_plural': 'CM_DotReguestFiles',
            },
        ),
    ]
