# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-11 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0345_auto_20191211_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='_file',
        ),
    ]
