# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-18 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0345_dotrequestfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationaction',
            name='sanction_outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_action', to='wildlifecompliance.SanctionOutcome'),
        ),
    ]
