# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-11 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0346_remove_artifact__file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentartifact',
            name='document_created_date',
        ),
        migrations.RemoveField(
            model_name='documentartifact',
            name='document_created_time',
        ),
        migrations.RemoveField(
            model_name='physicalartifact',
            name='artifact_created_date',
        ),
        migrations.RemoveField(
            model_name='physicalartifact',
            name='artifact_created_time',
        ),
        migrations.AddField(
            model_name='artifact',
            name='artifact_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='artifact_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
