# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-16 07:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0347_auto_20191211_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicalartifact',
            options={'verbose_name': 'CM_PhysicalArtifact', 'verbose_name_plural': 'CM_PhysicalArtifacts'},
        ),
        migrations.AlterField(
            model_name='physicalartifacttype',
            name='details_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[{}]),
        ),
        migrations.AlterField(
            model_name='physicalartifacttype',
            name='storage_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[{}]),
        ),
    ]
