# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-16 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0348_auto_20191216_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
