# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-18 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0351_remove_artifact_custodian'),
        ('wildlifecompliance', '0351_merge_20191218_1201'),
    ]

    operations = [
    ]
