# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-20 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0352_merge_20191218_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediationaction',
            name='status',
            field=models.CharField(blank=True, choices=[(b'due', b'Due'), (b'overdue', b'Overdue'), (b'submitted', b'Submitted'), (b'accepted', b'Accepted')], max_length=40),
        ),
        migrations.AlterField(
            model_name='remediationaction',
            name='sanction_outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_actions', to='wildlifecompliance.SanctionOutcome'),
        ),
    ]
