# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-20 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0353_auto_20191220_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationActionTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('remediation_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_taken', to='wildlifecompliance.RemediationAction')),
            ],
            options={
                'verbose_name': 'CM_RemediationActionTaken',
                'verbose_name_plural': 'CM_RemediationActionsTaken',
            },
        ),
        migrations.CreateModel(
            name='RemediationActionTakenDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=255, upload_to=b'')),
                ('remediation_action_taken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='wildlifecompliance.RemediationActionTaken')),
            ],
            options={
                'verbose_name': 'CM_RemediationActionTakenDocument',
                'verbose_name_plural': 'CM_RemediationActionTakenDocuments',
            },
        ),
    ]
