# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-23 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0352_legalcaserunningsheetartifacts'),
        ('wildlifecompliance', '0353_auto_20191220_1334'),
    ]

    operations = [
    ]
