# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-23 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0354_merge_20191223_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalcaserunningsheetartifacts',
            name='document_artifacts',
        ),
        migrations.RemoveField(
            model_name='legalcaserunningsheetartifacts',
            name='legal_case',
        ),
        migrations.RemoveField(
            model_name='legalcaserunningsheetartifacts',
            name='physical_artifacts',
        ),
        migrations.AddField(
            model_name='documentartifact',
            name='legal_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_case_document_artifacts', to='wildlifecompliance.LegalCase'),
        ),
        migrations.AddField(
            model_name='physicalartifact',
            name='legal_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_case_physical_artifacts', to='wildlifecompliance.LegalCase'),
        ),
        migrations.DeleteModel(
            name='LegalCaseRunningSheetArtifacts',
        ),
    ]
