# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-20 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0354_remediationactiontaken_remediationactiontakendocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediationactiontaken',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='remediationactiontaken',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
