# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-31 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0355_auto_20191223_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentartifact',
            name='legal_case',
        ),
        migrations.AddField(
            model_name='documentartifact',
            name='legal_case',
            field=models.ManyToManyField(related_name='legal_case_document_artifacts', to='wildlifecompliance.LegalCase'),
        ),
        migrations.RemoveField(
            model_name='physicalartifact',
            name='legal_case',
        ),
        migrations.AddField(
            model_name='physicalartifact',
            name='legal_case',
            field=models.ManyToManyField(related_name='legal_case_physical_artifacts', to='wildlifecompliance.LegalCase'),
        ),
    ]
