# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-03 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0356_auto_20191231_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentartifact',
            name='offender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_artifact_offender', to='wildlifecompliance.Offender'),
        ),
    ]
