# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-03 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0357_documentartifact_offender'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentartifact',
            name='interviewer_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='physicalartifact',
            name='officer_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
