# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-03 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0358_auto_20200103_1145'),
        ('wildlifecompliance', '0359_auto_20200102_1426'),
    ]

    operations = [
    ]
