# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-06 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0360_merge_20200103_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediationaction',
            name='remediation_action_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
