# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-06 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0360_merge_20200103_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentartifact',
            name='document_type',
            field=models.CharField(choices=[('witness_statement', 'witness_statement'), ('record_of_interview', 'record_of_interview'), ('officer_statement', 'officer_statement'), ('expert_statement', 'expert_statement'), ('photograph', 'photograph'), ('video', 'video'), ('sound', 'sound'), ('other', 'other')], default=None, max_length=30),
            preserve_default=False,
        ),
    ]
