# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-06 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0361_auto_20200106_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentartifact',
            name='document_type',
            field=models.CharField(choices=[('witness_statement', 'Witness Statement'), ('record_of_interview', 'Record of Interview'), ('officer_statement', 'Officer Statement'), ('expert_statement', 'Expert Statement'), ('photograph', 'Photograph'), ('video', 'Video'), ('sound', 'Sound'), ('other', 'Other')], max_length=30),
        ),
    ]
