# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-06 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0363_legalcase_associated_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcase',
            name='associated_persons',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
