# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-07 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0366_auto_20200107_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('document_object_disposal_period', 'Document Object Disposal Period'), ('physical_object_disposal_period', 'Physical Object Disposal Period')], max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
