# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-07 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0367_globalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('document_object_disposal_period', 'Document Object Disposal Period'), ('physical_object_disposal_period', 'Physical Object Disposal Period')], max_length=255, unique=True),
        ),
    ]
