# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-08 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0361_remediationaction_remediation_action_id'),
        ('wildlifecompliance', '0368_auto_20200107_1627'),
    ]

    operations = [
    ]
