# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-08 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0369_merge_20200108_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='remediationaction',
            name='status',
            field=models.CharField(blank=True, choices=[(b'open', b'Open'), (b'overdue', b'Overdue'), (b'submitted', b'Submitted'), (b'accepted', b'Accepted')], max_length=40),
        ),
    ]
