# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-08 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0371_auto_20200108_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='status',
            new_name='artifact_status',
        ),
    ]
