# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-09 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0372_auto_20200109_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='artifact_status',
            new_name='status',
        ),
    ]
