# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-10 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0374_remediationactionnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remediationactionnotification',
            name='sanction_outcome',
        ),
        migrations.AddField(
            model_name='remediationactionnotification',
            name='remediation_action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.RemediationAction'),
            preserve_default=False,
        ),
    ]
