# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-10 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0376_auto_20200110_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationActionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=30)),
                ('remediation_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='wildlifecompliance.RemediationAction')),
                ('sanction_outcome_comms_log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.SanctionOutcomeCommsLogEntry')),
            ],
            options={
                'verbose_name': 'CM_RemediationActionNotification',
                'verbose_name_plural': 'CM_RemediationActionNotifications',
            },
        ),
    ]
