# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-13 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0193_auto_20191227_1146'),
        ('wildlifecompliance', '0377_remediationactionnotification'),
    ]

    operations = [
    ]
