# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-15 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0379_compliancemanagementemailuser'),
        ('wildlifecompliance', '0194_auto_20200115_1526'),
    ]

    operations = [
    ]
