# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-15 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0381_auto_20200115_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalartifacttype',
            name='artifact_type',
            field=models.CharField(choices=[('found_object', 'Found Object'), ('seized_object', 'Seized Object'), ('surrendered_object', 'Surrendered Object')], max_length=50, unique=True),
        ),
    ]
