# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-16 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0380_merge_20200115_1723'),
        ('wildlifecompliance', '0383_auto_20200115_1554'),
    ]

    operations = [
    ]
