# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-16 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0384_merge_20200116_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendererDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=255, upload_to=b'')),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renderer_documents', to='wildlifecompliance.PhysicalArtifact')),
            ],
        ),
        migrations.RemoveField(
            model_name='detailsdocument',
            name='log_entry',
        ),
        migrations.RemoveField(
            model_name='storagedocument',
            name='log_entry',
        ),
        migrations.DeleteModel(
            name='DetailsDocument',
        ),
        migrations.DeleteModel(
            name='StorageDocument',
        ),
    ]
