# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-21 01:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0384_merge_20200116_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionOutcomeDocumentAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sanction_outcome_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='wildlifecompliance.SanctionOutcomeDocument')),
            ],
            options={
                'verbose_name': 'CM_SanctionOutcomeDocumentAccessLog',
                'verbose_name_plural': 'CM_SanctionOutcomeDocumentAccessLogs',
            },
        ),
    ]
