# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-17 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0385_auto_20200116_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendererdocument',
            old_name='log_entry',
            new_name='physical_artifact',
        ),
        migrations.AddField(
            model_name='rendererdocument',
            name='input_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
