# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-17 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0387_temporarydocument_input_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarydocument',
            name='input_name',
        ),
        migrations.AddField(
            model_name='temporarydocumentcollection',
            name='input_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
