# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-21 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0391_legalcase_statement_of_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcase',
            name='pb_accused_bad_character',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_accused_bad_character_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_applications_orders_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_applications_orders_requests_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_applications_orders_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_applications_orders_required_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_further_persons_interviews_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_further_persons_interviews_pending_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_local_public_interest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_local_public_interest_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_other_interviews',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_other_interviews_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_other_legal_matters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_other_legal_matters_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_other_persons_receiving_sanction_outcome',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_other_persons_receiving_sanction_outcome_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_problems_needs_prosecution_witnesses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_problems_needs_prosecution_witnesses_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_relevant_persons_pending_charges',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_relevant_persons_pending_charges_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_statement_of_facts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_statements_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_statements_pending_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_victim_impact_statement_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_victim_impact_statement_taken_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_vulnerable_hostile_witnesses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_vulnerable_hostile_witnesses_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_witness_refusing_statement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='pb_witness_refusing_statement_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
