# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-21 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0392_auto_20200121_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentartifact',
            old_name='legal_case',
            new_name='associated_legal_cases',
        ),
        migrations.AddField(
            model_name='documentartifact',
            name='primary_legal_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_case_document_artifacts_primary', to='wildlifecompliance.LegalCase'),
        ),
    ]
