# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-21 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0393_auto_20200121_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentartifact',
            old_name='primary_legal_case',
            new_name='legal_case',
        ),
    ]
