# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-21 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0394_auto_20200121_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalartifact',
            name='associated_legal_cases',
            field=models.ManyToManyField(related_name='legal_case_physical_artifacts', to='wildlifecompliance.LegalCase'),
        ),
        migrations.RemoveField(
            model_name='physicalartifact',
            name='legal_case',
        ),
        migrations.AddField(
            model_name='physicalartifact',
            name='legal_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_case_physical_artifacts_primary', to='wildlifecompliance.LegalCase'),
        ),
    ]
