# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-23 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0395_auto_20200121_1157'),
        ('wildlifecompliance', '0385_sanctionoutcomedocumentaccesslog'),
    ]

    operations = [
    ]
