# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-22 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0395_auto_20200121_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefOfEvidenceRecordOfInterviewTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('ticked', models.BooleanField(default=False)),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_case_brief_of_evidence_record_of_interview_tree', to='wildlifecompliance.LegalCase')),
            ],
        ),
    ]
