# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-30 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0395_auto_20200121_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='selected_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_attachments', to='wildlifecompliance.ApplicationSelectedActivity'),
        ),
    ]
