# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-04 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0396_applicationdocument_selected_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcondition',
            name='licence_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.LicencePurpose'),
        ),
        migrations.AddField(
            model_name='applicationcondition',
            name='source_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.ActivityPermissionGroup'),
        ),
    ]
