# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-31 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0396_merge_20200123_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanctionoutcome',
            name='payment_status',
        ),
    ]
