# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-05 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0397_auto_20200204_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSelectedActivityPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_status', models.CharField(choices=[('propose', 'Proposed for Issue'), ('decline', 'Declined'), ('issue', 'Issued')], default='propose', max_length=40, verbose_name='Processing Status')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_activity_proposed_purpose', to='wildlifecompliance.LicencePurpose')),
                ('selected_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_purposes', to='wildlifecompliance.ApplicationSelectedActivity')),
            ],
            options={
                'verbose_name': 'Application selected activity purpose',
            },
        ),
        migrations.AlterModelOptions(
            name='applicationstandardcondition',
            options={'verbose_name': 'Standard condition'},
        ),
    ]
