# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-22 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0397_auto_20200122_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefOfEvidenceRecordOfInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticked', models.BooleanField(default=False)),
                ('associated_doc_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_artifact_boe_roi', to='wildlifecompliance.DocumentArtifact')),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_case_boe_roi', to='wildlifecompliance.LegalCase')),
                ('offence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offence_boe_roi', to='wildlifecompliance.Offence')),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offender_boe_roi', to='wildlifecompliance.LegalCase')),
                ('record_of_interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_of_interview_boe_roi', to='wildlifecompliance.DocumentArtifact')),
            ],
        ),
    ]
