# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-22 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0398_briefofevidencerecordofinterview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefofevidencerecordofinterview',
            name='associated_doc_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_artifact_boe_roi', to='wildlifecompliance.DocumentArtifact'),
        ),
        migrations.AlterField(
            model_name='briefofevidencerecordofinterview',
            name='offender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offender_boe_roi', to='wildlifecompliance.LegalCase'),
        ),
        migrations.AlterField(
            model_name='briefofevidencerecordofinterview',
            name='record_of_interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_of_interview_boe_roi', to='wildlifecompliance.DocumentArtifact'),
        ),
    ]
