# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-31 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0398_auto_20200131_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfringementPenaltyInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_reference', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='infringementpenalty',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='infringementpenalty',
            name='sanction_outcome',
        ),
        migrations.AddField(
            model_name='sanctionoutcome',
            name='infringement_penalty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.InfringementPenalty'),
        ),
        migrations.AddField(
            model_name='infringementpenaltyinvoice',
            name='infringement_penalty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infringement_penalty_invoices', to='wildlifecompliance.InfringementPenalty'),
        ),
    ]
