# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-04 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0399_auto_20200131_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionoutcome',
            name='infringement_penalty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanction_outcome', to='wildlifecompliance.InfringementPenalty'),
        ),
    ]
