# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-04 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0400_auto_20200204_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionoutcome',
            name='payment_status',
            field=models.CharField(blank=True, choices=[(b'unpaid', b'Unpaid'), (b'partially_paid', b'Partially Paid'), (b'paid', b'Paid'), (b'over_paid', b'Over Paid')], max_length=30),
        ),
    ]
