# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-30 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0402_auto_20200129_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefofevidencerecordofinterview',
            name='children',
            field=models.ManyToManyField(related_name='parents', to='wildlifecompliance.BriefOfEvidenceRecordOfInterview'),
        ),
    ]
