# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-31 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0403_auto_20200130_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentartifact',
            old_name='interviewer_email',
            new_name='officer_interviewer_email',
        ),
    ]
