# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-04 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0401_sanctionoutcome_payment_status'),
        ('wildlifecompliance', '0403_auto_20200130_1347'),
    ]

    operations = [
    ]
