# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-31 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0404_auto_20200131_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefOfEvidenceOtherStatements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=255, null=True)),
                ('associated_doc_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_artifact_boe_other_statements', to='wildlifecompliance.DocumentArtifact')),
                ('statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement_boe_other_statements', to='wildlifecompliance.DocumentArtifact')),
            ],
        ),
    ]
