# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-31 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0407_briefofevidenceotherstatements_legal_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefofevidenceotherstatements',
            name='legal_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_case_boe_other_statements', to='wildlifecompliance.LegalCase'),
        ),
    ]
