# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-03 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0408_auto_20200131_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentartifact',
            name='interviewer',
        ),
        migrations.AddField(
            model_name='documentartifact',
            name='officer_interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_artifact_officer_interviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
