# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-04 06:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0411_auto_20200204_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefofevidenceotherstatements',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_user_boe_other_statements', to=settings.AUTH_USER_MODEL),
        ),
    ]
