# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-05 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0404_merge_20200204_1623'),
        ('wildlifecompliance', '0412_auto_20200204_1402'),
    ]

    operations = [
    ]
