# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-05 06:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0413_merge_20200205_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtProceedings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_outcome_details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourtProceedingsJournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('row_num', models.SmallIntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('court_proceedings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='wildlifecompliance.CourtProceedings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='legalcase',
            name='court_proceedings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_case', to='wildlifecompliance.CourtProceedings'),
        ),
        migrations.AlterUniqueTogether(
            name='courtproceedingsjournalentry',
            unique_together=set([('court_proceedings', 'row_num')]),
        ),
    ]
