# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-05 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0416_auto_20200205_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefOfEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_of_facts', models.TextField(blank=True, null=True)),
                ('victim_impact_statement_taken', models.BooleanField(default=False)),
                ('statements_pending', models.BooleanField(default=False)),
                ('vulnerable_hostile_witnesses', models.BooleanField(default=False)),
                ('witness_refusing_statement', models.BooleanField(default=False)),
                ('problems_needs_prosecution_witnesses', models.BooleanField(default=False)),
                ('accused_bad_character', models.BooleanField(default=False)),
                ('further_persons_interviews_pending', models.BooleanField(default=False)),
                ('other_interviews', models.BooleanField(default=False)),
                ('relevant_persons_pending_charges', models.BooleanField(default=False)),
                ('other_persons_receiving_sanction_outcome', models.BooleanField(default=False)),
                ('local_public_interest', models.BooleanField(default=False)),
                ('applications_orders_requests', models.BooleanField(default=False)),
                ('applications_orders_required', models.BooleanField(default=False)),
                ('other_legal_matters', models.BooleanField(default=False)),
                ('victim_impact_statement_taken_details', models.TextField(blank=True, null=True)),
                ('statements_pending_details', models.TextField(blank=True, null=True)),
                ('vulnerable_hostile_witnesses_details', models.TextField(blank=True, null=True)),
                ('witness_refusing_statement_details', models.TextField(blank=True, null=True)),
                ('problems_needs_prosecution_witnesses_details', models.TextField(blank=True, null=True)),
                ('accused_bad_character_details', models.TextField(blank=True, null=True)),
                ('further_persons_interviews_pending_details', models.TextField(blank=True, null=True)),
                ('other_interviews_details', models.TextField(blank=True, null=True)),
                ('relevant_persons_pending_charges_details', models.TextField(blank=True, null=True)),
                ('other_persons_receiving_sanction_outcome_details', models.TextField(blank=True, null=True)),
                ('local_public_interest_details', models.TextField(blank=True, null=True)),
                ('applications_orders_requests_details', models.TextField(blank=True, null=True)),
                ('applications_orders_required_details', models.TextField(blank=True, null=True)),
                ('other_legal_matters_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProsecutionBrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_of_facts', models.TextField(blank=True, null=True)),
                ('victim_impact_statement_taken', models.BooleanField(default=False)),
                ('statements_pending', models.BooleanField(default=False)),
                ('vulnerable_hostile_witnesses', models.BooleanField(default=False)),
                ('witness_refusing_statement', models.BooleanField(default=False)),
                ('problems_needs_prosecution_witnesses', models.BooleanField(default=False)),
                ('accused_bad_character', models.BooleanField(default=False)),
                ('further_persons_interviews_pending', models.BooleanField(default=False)),
                ('other_interviews', models.BooleanField(default=False)),
                ('relevant_persons_pending_charges', models.BooleanField(default=False)),
                ('other_persons_receiving_sanction_outcome', models.BooleanField(default=False)),
                ('local_public_interest', models.BooleanField(default=False)),
                ('applications_orders_requests', models.BooleanField(default=False)),
                ('applications_orders_required', models.BooleanField(default=False)),
                ('other_legal_matters', models.BooleanField(default=False)),
                ('victim_impact_statement_taken_details', models.TextField(blank=True, null=True)),
                ('statements_pending_details', models.TextField(blank=True, null=True)),
                ('vulnerable_hostile_witnesses_details', models.TextField(blank=True, null=True)),
                ('witness_refusing_statement_details', models.TextField(blank=True, null=True)),
                ('problems_needs_prosecution_witnesses_details', models.TextField(blank=True, null=True)),
                ('accused_bad_character_details', models.TextField(blank=True, null=True)),
                ('further_persons_interviews_pending_details', models.TextField(blank=True, null=True)),
                ('other_interviews_details', models.TextField(blank=True, null=True)),
                ('relevant_persons_pending_charges_details', models.TextField(blank=True, null=True)),
                ('other_persons_receiving_sanction_outcome_details', models.TextField(blank=True, null=True)),
                ('local_public_interest_details', models.TextField(blank=True, null=True)),
                ('applications_orders_requests_details', models.TextField(blank=True, null=True)),
                ('applications_orders_required_details', models.TextField(blank=True, null=True)),
                ('other_legal_matters_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='accused_bad_character',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='accused_bad_character_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='applications_orders_requests',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='applications_orders_requests_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='applications_orders_required',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='applications_orders_required_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='further_persons_interviews_pending',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='further_persons_interviews_pending_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='local_public_interest',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='local_public_interest_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='other_interviews',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='other_interviews_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='other_legal_matters',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='other_legal_matters_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='other_persons_receiving_sanction_outcome',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='other_persons_receiving_sanction_outcome_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_accused_bad_character',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_accused_bad_character_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_applications_orders_requests',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_applications_orders_requests_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_applications_orders_required',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_applications_orders_required_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_further_persons_interviews_pending',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_further_persons_interviews_pending_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_local_public_interest',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_local_public_interest_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_other_interviews',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_other_interviews_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_other_legal_matters',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_other_legal_matters_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_other_persons_receiving_sanction_outcome',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_other_persons_receiving_sanction_outcome_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_problems_needs_prosecution_witnesses',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_problems_needs_prosecution_witnesses_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_relevant_persons_pending_charges',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_relevant_persons_pending_charges_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_statement_of_facts',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_statements_pending',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_statements_pending_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_victim_impact_statement_taken',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_victim_impact_statement_taken_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_vulnerable_hostile_witnesses',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_vulnerable_hostile_witnesses_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_witness_refusing_statement',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='pb_witness_refusing_statement_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='problems_needs_prosecution_witnesses',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='problems_needs_prosecution_witnesses_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='relevant_persons_pending_charges',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='relevant_persons_pending_charges_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='statement_of_facts',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='statements_pending',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='statements_pending_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='victim_impact_statement_taken',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='victim_impact_statement_taken_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='vulnerable_hostile_witnesses',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='vulnerable_hostile_witnesses_details',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='witness_refusing_statement',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='witness_refusing_statement_details',
        ),
        migrations.AddField(
            model_name='legalcase',
            name='brief_of_evidence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_case', to='wildlifecompliance.BriefOfEvidence'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='prosecution_brief',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_case', to='wildlifecompliance.ProsecutionBrief'),
        ),
    ]
