# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-06 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0417_auto_20200205_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalcase',
            name='brief_of_evidence',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='prosecution_brief',
        ),
        migrations.AddField(
            model_name='briefofevidence',
            name='legal_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brief_of_evidence', to='wildlifecompliance.LegalCase'),
        ),
        migrations.AddField(
            model_name='prosecutionbrief',
            name='legal_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prosecution_brief', to='wildlifecompliance.LegalCase'),
        ),
    ]
