# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-07 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0418_auto_20200206_1650'),
        ('wildlifecompliance', '0398_auto_20200205_1658'),
    ]

    operations = [
    ]
