# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-12 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wildlifecompliance.components.legal_case.models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0419_auto_20200207_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtOutcomeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=255, upload_to=wildlifecompliance.components.legal_case.models.update_court_outcome_doc_filename)),
                ('court_proceedings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_outcome_documents', to='wildlifecompliance.CourtProceedings')),
            ],
            options={
                'verbose_name': 'CM_CourtOutcomeDocument',
                'verbose_name_plural': 'CM_CourtOutcomeDocuments',
            },
        ),
    ]
