# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-11 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0419_briefofevidencedocumentartifacts_briefofevidencephysicalartifacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentArtifactLegalCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'CM_DocumentArtifactLegalCases',
            },
        ),
        migrations.CreateModel(
            name='PhysicalArtifactLegalCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('used_within_case', models.BooleanField(default=False)),
                ('sensitive_non_disclosable', models.BooleanField(default=False)),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.LegalCase')),
            ],
            options={
                'verbose_name': 'CM_PhysicalArtifactLegalCases',
            },
        ),
        migrations.RemoveField(
            model_name='documentartifact',
            name='associated_legal_cases',
        ),
        migrations.RemoveField(
            model_name='documentartifact',
            name='legal_case',
        ),
        migrations.RemoveField(
            model_name='physicalartifact',
            name='associated_legal_cases',
        ),
        migrations.RemoveField(
            model_name='physicalartifact',
            name='legal_case',
        ),
        migrations.AddField(
            model_name='physicalartifactlegalcases',
            name='physical_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.PhysicalArtifact'),
        ),
        migrations.AddField(
            model_name='documentartifactlegalcases',
            name='document_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.DocumentArtifact'),
        ),
        migrations.AddField(
            model_name='documentartifactlegalcases',
            name='legal_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.LegalCase'),
        ),
        migrations.AddField(
            model_name='documentartifact',
            name='legal_cases',
            field=models.ManyToManyField(related_name='legal_case_document_artifacts', through='wildlifecompliance.DocumentArtifactLegalCases', to='wildlifecompliance.LegalCase'),
        ),
        migrations.AddField(
            model_name='physicalartifact',
            name='legal_cases',
            field=models.ManyToManyField(related_name='legal_case_physical_artifacts', through='wildlifecompliance.PhysicalArtifactLegalCases', to='wildlifecompliance.LegalCase'),
        ),
    ]
