# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-07 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0419_merge_20200207_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuanceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=25, upload_to=b'')),
                ('can_delete', models.BooleanField(default=True)),
                ('selected_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuance_documents', to='wildlifecompliance.ApplicationSelectedActivity')),
            ],
        ),
        migrations.RemoveField(
            model_name='applicationdocument',
            name='selected_activity',
        ),
    ]
