# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-12 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0420_courtoutcomedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_datetime', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('court_proceedings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_dates', to='wildlifecompliance.CourtProceedings')),
            ],
            options={
                'verbose_name': 'CM_CourtDate',
                'verbose_name_plural': 'CM_CourtDates',
            },
        ),
    ]
