# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-07 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0420_auto_20200207_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuancedocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=b''),
        ),
    ]
