# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-12 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0419_briefofevidencedocumentartifacts_briefofevidencephysicalartifacts'),
        ('wildlifecompliance', '0421_courtdate'),
    ]

    operations = [
    ]
