# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-10 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0421_auto_20200207_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicencePurposeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('detail', models.CharField(max_length=100)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_information', to='wildlifecompliance.LicencePurpose')),
            ],
            options={
                'verbose_name': 'Licence purpose additional information',
                'verbose_name_plural': 'Licence purpose additional information',
            },
        ),
    ]
