# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-11 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0422_auto_20200211_1501'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentartifactlegalcases',
            unique_together=set([('document_artifact', 'legal_case')]),
        ),
        migrations.AlterUniqueTogether(
            name='physicalartifactlegalcases',
            unique_together=set([('physical_artifact', 'legal_case')]),
        ),
    ]
