# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-14 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0423_auto_20200212_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalartifactlegalcases',
            name='reason_sensitive_non_disclosable',
            field=models.TextField(blank=True, null=True),
        ),
    ]
