# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-10 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0423_auto_20200210_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licencepurposedetail',
            options={'ordering': ['purpose', 'index'], 'verbose_name': 'Licence purpose additional information', 'verbose_name_plural': 'Licence purpose additional information'},
        ),
    ]
