# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-10 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0424_auto_20200210_1152'),
        ('wildlifecompliance', '0419_briefofevidencedocumentartifacts_briefofevidencephysicalartifacts'),
    ]

    operations = [
    ]
