# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-14 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0426_auto_20200212_1624'),
        ('wildlifecompliance', '0424_physicalartifactlegalcases_reason_sensitive_non_disclosable'),
    ]

    operations = [
    ]
