# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-19 22:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0427_merge_20200214_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assigned_assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_assessor', to=settings.AUTH_USER_MODEL),
        ),
    ]
