# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-14 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0427_merge_20200214_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='briefofevidencephysicalartifacts',
            old_name='details',
            new_name='reason_sensitive_non_disclosable',
        ),
        migrations.RenameField(
            model_name='prosecutionbriefphysicalartifacts',
            old_name='details',
            new_name='reason_sensitive_non_disclosable',
        ),
        migrations.RemoveField(
            model_name='physicalartifactlegalcases',
            name='reason_sensitive_non_disclosable',
        ),
    ]
