# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-17 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0428_auto_20200214_1405'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='briefofevidencedocumentartifacts',
            unique_together=set([('document_artifact', 'legal_case')]),
        ),
        migrations.AlterUniqueTogether(
            name='briefofevidencephysicalartifacts',
            unique_together=set([('physical_artifact', 'legal_case')]),
        ),
        migrations.AlterUniqueTogether(
            name='prosecutionbriefdocumentartifacts',
            unique_together=set([('document_artifact', 'legal_case')]),
        ),
        migrations.AlterUniqueTogether(
            name='prosecutionbriefphysicalartifacts',
            unique_together=set([('physical_artifact', 'legal_case')]),
        ),
    ]
