# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-18 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0430_briefofevidencedocument'),
        ('wildlifecompliance', '0427_merge_20200214_1614'),
    ]

    operations = [
    ]
