# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-21 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0428_assessment_assigned_assessor'),
        ('wildlifecompliance', '0431_merge_20200218_1801'),
    ]

    operations = [
    ]
