# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-19 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0432_prosecutionbriefdocument_prosecutionbriefotherstatements_prosecutionbriefrecordofinterview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcase',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('await_endorsement', 'Awaiting Endorsement'), ('discarded', 'Discarded'), ('brief_of_evidence', 'Brief of Evidence'), ('prosecution_brief', 'Prosecution Brief'), ('closed', 'Closed'), ('pending_closure', 'Pending Closure')], default='open', max_length=100),
        ),
    ]
