# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-21 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0432_merge_20200221_1126'),
        ('wildlifecompliance', '0434_auto_20200221_1352'),
    ]

    operations = [
    ]
