# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-03 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0438_legalcasegenerateddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='offence',
            name='occurrence_datetime_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
