# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-06 15:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0441_auto_20200303_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSpecieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie_id', models.IntegerField(blank=True, null=True)),
                ('retrieve_date', models.DateTimeField(blank=True, null=True)),
                ('authorised_on', models.DateTimeField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Application Species',
            },
        ),
        migrations.AlterField(
            model_name='applicationformdatarecord',
            name='component_type',
            field=models.CharField(choices=[('text', 'Text'), ('tab', 'Tab'), ('section', 'Section'), ('group', 'Group'), ('number', 'Number'), ('email', 'Email'), ('select', 'Select'), ('multi-select', 'Multi-Select'), ('text_area', 'Text Area'), ('table', 'Table'), ('expander_table', 'Expander Table'), ('label', 'Label'), ('radiobuttons', 'Radio'), ('checkbox', 'Checkbox'), ('declaration', 'Declaration'), ('file', 'File'), ('date', 'Date'), ('species_list', 'Species List')], default='text', max_length=64),
        ),
    ]
