# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-08 00:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0442_auto_20200306_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie_id', models.IntegerField(unique=True)),
                ('verify_date', models.DateTimeField(auto_now=True)),
                ('verify_id', models.CharField(blank=True, max_length=256, null=True)),
                ('verify_token', models.CharField(blank=True, max_length=256, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Licence Species',
            },
        ),
        migrations.DeleteModel(
            name='ApplicationSpecieList',
        ),
    ]
