# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-08 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0443_auto_20200308_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licencespecies',
            options={'verbose_name': 'Licence species'},
        ),
    ]
