# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-12 06:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0445_auto_20200309_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformdatarecord',
            name='component_attribute',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationformdatarecord',
            name='component_type',
            field=models.CharField(choices=[('text', 'Text'), ('tab', 'Tab'), ('section', 'Section'), ('group', 'Group'), ('number', 'Number'), ('email', 'Email'), ('select', 'Select'), ('multi-select', 'Multi-Select'), ('text_area', 'Text Area'), ('table', 'Table'), ('expander_table', 'Expander Table'), ('label', 'Label'), ('radiobuttons', 'Radio'), ('checkbox', 'Checkbox'), ('declaration', 'Declaration'), ('file', 'File'), ('date', 'Date'), ('species', 'Select Species')], default='text', max_length=64),
        ),
    ]
