# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-11 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0442_auto_20200310_0945'),
        ('wildlifecompliance', '0445_auto_20200309_1556'),
    ]

    operations = [
    ]
