# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-12 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0446_merge_20200311_1311'),
        ('wildlifecompliance', '0446_auto_20200312_1455'),
    ]

    operations = [
    ]
