# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-19 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0447_merge_20200312_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSelectedActivityInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('request_datetime', models.DateTimeField(auto_now=True)),
                ('selected_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='wildlifecompliance.ApplicationSelectedActivity')),
            ],
        ),
    ]
