# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-20 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0448_applicationselectedactivityinspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_datetime', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='wildlifecompliance.Assessment')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_inspection', to='wildlifecompliance.Inspection')),
            ],
        ),
        migrations.RemoveField(
            model_name='applicationselectedactivityinspection',
            name='selected_activity',
        ),
        migrations.DeleteModel(
            name='ApplicationSelectedActivityInspection',
        ),
    ]
