# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-24 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0449_auto_20200324_1345'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legalcasepriority',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='legalcasepriority',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='legalcasepriority',
            name='description',
        ),
        migrations.RemoveField(
            model_name='legalcasepriority',
            name='replaced_by',
        ),
        migrations.RemoveField(
            model_name='legalcasepriority',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='legalcasepriority',
            name='version',
        ),
    ]
