# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-20 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0449_auto_20200320_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='inspection_comment',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='inspection_date',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='inspection_report',
        ),
    ]
