# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-23 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0450_auto_20200320_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultcondition',
            name='licence_purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_purpose', to='wildlifecompliance.LicencePurpose'),
        ),
        migrations.AlterField(
            model_name='defaultcondition',
            name='licence_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_activity', to='wildlifecompliance.LicenceActivity'),
        ),
        migrations.AlterField(
            model_name='defaultcondition',
            name='standard_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_condition', to='wildlifecompliance.ApplicationStandardCondition'),
        ),
    ]
