# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-24 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0451_auto_20200323_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencepurposedetail',
            name='purpose',
        ),
        migrations.AddField(
            model_name='applicationstandardcondition',
            name='additional_information',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.DeleteModel(
            name='LicencePurposeDetail',
        ),
    ]
