# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-24 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0452_auto_20200324_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstandardcondition',
            name='additional_information',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
