# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-25 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0448_auto_20200320_1241'),
        ('wildlifecompliance', '0453_auto_20200324_1553'),
    ]

    operations = [
    ]
