# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-30 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0455_merge_20200326_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtHearingNoticeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=255, upload_to=b'')),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_hearing_notices', to='wildlifecompliance.LegalCase')),
            ],
            options={
                'verbose_name': 'CM_CourtHearingNoticeDocument',
                'verbose_name_plural': 'CM_CourtHearingNoticeDocuments',
            },
        ),
        migrations.CreateModel(
            name='ProsecutionNoticeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=255, upload_to=b'')),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosecution_notices', to='wildlifecompliance.LegalCase')),
            ],
            options={
                'verbose_name': 'CM_ProsecutionNoticeDocument',
                'verbose_name_plural': 'CM_ProsecutionNoticeDocuments',
            },
        ),
    ]
