# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-27 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0455_merge_20200326_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcase',
            name='case_created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalcase',
            name='case_created_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
