# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-31 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0456_courthearingnoticedocument_prosecutionnoticedocument'),
        ('wildlifecompliance', '0456_auto_20200327_1003'),
    ]

    operations = [
    ]
