# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-06 08:16
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0457_merge_20200331_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcondition',
            name='licence_purpose',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='licence_activity', chained_model_field='licence_activity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_purpose', to='wildlifecompliance.LicencePurpose'),
        ),
    ]
