# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-08 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0458_auto_20200407_1507'),
        ('wildlifecompliance', '0458_auto_20200406_1616'),
    ]

    operations = [
    ]
