# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-08 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0459_merge_20200407_1705'),
        ('wildlifecompliance', '0459_merge_20200408_1017'),
    ]

    operations = [
    ]
