# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-08 06:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0460_merge_20200408_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationselectedactivity',
            name='additional_licence_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
