# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-15 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0462_auto_20200414_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtOutcomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CM_CourtOutcomeType',
                'verbose_name_plural': 'CM_CourtOutcomeTypes',
            },
        ),
    ]
