# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-15 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0463_courtoutcometype'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtproceedings',
            name='court_outcome_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='courtproceedings',
            name='court_outcome_fine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fine'),
        ),
        migrations.AddField(
            model_name='courtproceedings',
            name='court_outcome_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.CourtOutcomeType'),
        ),
    ]
