# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-15 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0464_auto_20200415_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtproceedings',
            name='court_outcome_cost',
        ),
        migrations.RemoveField(
            model_name='courtproceedings',
            name='court_outcome_fine',
        ),
        migrations.AddField(
            model_name='courtproceedings',
            name='court_outcome_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costs'),
        ),
        migrations.AddField(
            model_name='courtproceedings',
            name='court_outcome_fines',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fines'),
        ),
    ]
