# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-20 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0465_auto_20200415_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='informed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
