# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-17 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0462_auto_20200417_0938'),
        ('wildlifecompliance', '0465_auto_20200415_1227'),
    ]

    operations = [
    ]
