# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-20 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0466_inspection_informed_datetime'),
        ('wildlifecompliance', '0466_merge_20200417_1601'),
    ]

    operations = [
    ]
