# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-23 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0467_merge_20200420_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_datetime', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_licence_inspection', to='wildlifecompliance.Inspection')),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_inspections', to='wildlifecompliance.WildlifeLicence')),
            ],
        ),
    ]
