# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-24 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0469_auto_20200424_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationselectedactivitypurpose',
            name='additional_fee',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8),
        ),
        migrations.AddField(
            model_name='applicationselectedactivitypurpose',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8),
        ),
        migrations.AddField(
            model_name='applicationselectedactivitypurpose',
            name='licence_fee',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8),
        ),
    ]
