# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-27 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0471_auto_20200424_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationselectedactivitypurpose',
            old_name='additional_fee',
            new_name='adjusted_fee',
        ),
    ]
