# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-28 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0472_auto_20200427_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationselectedactivity',
            name='decision_action',
            field=models.CharField(choices=[('default', 'Default'), ('declined', 'Declined'), ('issued', 'Issued'), ('reissue', 'Re-issue')], default='default', max_length=20, verbose_name='Action'),
        ),
    ]
