# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-31 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0475_auto_20200515_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationselectedactivitypurpose',
            name='proposed_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationselectedactivitypurpose',
            name='proposed_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
