# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-19 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0478_auto_20200618_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeLicenceReceptionEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
    ]
