# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-21 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0479_wildlifelicencereceptionemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinvoice',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'Credit Card'), (1, 'BPAY'), (2, 'Monthly Invoicing'), (3, 'Other'), (4, 'Other - Cash'), (5, 'Other - None')], default=0),
        ),
    ]
