# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-21 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0480_applicationinvoice_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationinvoice',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='applicationinvoice',
            name='other_payment_method',
            field=models.CharField(blank=True, choices=[('other', 'Invoice for Other Payment'), ('cash', 'Invoice for Cash'), ('none', 'Invoice for No Payment')], max_length=50, null=True),
        ),
    ]
