# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-23 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0481_auto_20200621_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submit_type',
            field=models.CharField(default='online', max_length=30, verbose_name='Submission Types'),
        ),
    ]
