# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-23 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0482_application_submit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='submit_type',
            field=models.CharField(choices=[('paper', 'Paper'), ('online', 'Online'), ('migrate', 'Migrate')], default='online', max_length=30, verbose_name='Submission Types'),
        ),
    ]
