# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-30 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0483_auto_20200623_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_status', models.CharField(choices=[('create', 'Created'), ('transfer', 'Transferred'), ('payment', 'Pay Transfer')], default='create', max_length=20)),
                ('status', models.CharField(choices=[('complete', 'Completed'), ('decline', 'Transfer Declined'), ('accept', 'Transfer Accepted'), ('notify', 'Notified Licensee'), ('awaiting', 'Awaiting Payment')], default='complete', max_length=20)),
                ('activity_type', models.CharField(choices=[('stock', 'Stock'), ('in_import', 'In through Import'), ('in_birth', 'In through Birth'), ('in_transfer', 'In through Transfer'), ('out_export', 'Out through Export'), ('out_death', 'Out through Death'), ('out_other', 'Out through Transfer'), ('out_dealer', 'Out through Dealer Transfer')], default='stock', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('stock_name', models.TextField(blank=True, null=True)),
                ('stock_quantity', models.IntegerField(default='0')),
                ('fee', models.DecimalField(decimal_places=2, default='0', max_digits=8)),
                ('licence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_licences', to='wildlifecompliance.WildlifeLicence')),
                ('licence_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_activities', to='wildlifecompliance.Return')),
            ],
        ),
    ]
