# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-01 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0484_returnactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnactivity',
            name='activity_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='returnactivity',
            name='stock_id',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='returnactivity',
            name='activity_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('in_import', 'Stock'), ('in_birth', 'In through Birth'), ('in_transfer', 'In through Transfer'), ('out_export', 'Out through Export'), ('out_death', 'Out through Death'), ('out_other', 'Out through Transfer'), ('out_dealer', 'Out through Dealer Transfer')], default='stock', max_length=20),
        ),
    ]
