# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-07 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0485_auto_20200701_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationslogentry',
            name='log_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('mail', 'Mail'), ('person', 'In Person'), ('file_note', 'File Note')], default='email', max_length=20),
        ),
    ]
