# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-12 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0487_auto_20200708_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenceactivity',
            name='oracle_account_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='returntype',
            name='oracle_account_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
