# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-13 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0489_returnlogdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licencepurpose',
            old_name='amendment_fee',
            new_name='amendment_application_fee',
        ),
        migrations.RenameField(
            model_name='licencepurpose',
            old_name='renewal_fee',
            new_name='renewal_application_fee',
        ),
        migrations.AddField(
            model_name='licencepurpose',
            name='apply_for_org',
            field=models.BooleanField(default=False, help_text='If ticked, the licenced Purpose can be on behalf of Org.'),
        ),
        migrations.AddField(
            model_name='licencepurpose',
            name='apply_multiple',
            field=models.BooleanField(default=False, help_text='If ticked, the licenced Purpose can have multiple periods.'),
        ),
    ]
