# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-13 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0490_auto_20200713_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationselectedactivitypurpose',
            name='purpose_sequence',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
