# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-15 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0491_applicationselectedactivitypurpose_purpose_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencepurpose',
            name='apply_for_org',
        ),
    ]
