# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-29 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0493_auto_20200728_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationselectedactivitypurpose',
            name='sent_renewal',
            field=models.BooleanField(default=False, help_text='If ticked, a renew reminder has been sent to applicant.'),
        ),
    ]
