# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-13 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0496_auto_20200729_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='returntype',
            name='species_required',
            field=models.BooleanField(default=False),
        ),
    ]
