# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-16 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0496_auto_20200729_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationselectedactivity',
            name='payment_status',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
