# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-16 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0497_returntype_species_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationselectedactivitypurpose',
            name='adjusted_licence_fee',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8),
        ),
    ]
