# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-17 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0497_applicationselectedactivity_payment_status'),
        ('wildlifecompliance', '0498_applicationselectedactivitypurpose_adjusted_licence_fee'),
    ]

    operations = [
    ]
