# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-17 04:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0499_merge_20200817_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationselectedactivity',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='applicationselectedactivitypurpose',
            name='adjusted_licence_fee',
        ),
        migrations.AddField(
            model_name='applicationselectedactivity',
            name='property_cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
