# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-18 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0502_application_property_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityinvoiceline',
            name='invoice_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activityinvoiceline',
            name='invoice_line_type',
            field=models.CharField(blank=True, choices=[('additional', 'Invoice line for Additional Fees'), ('application', 'Invoice line for Application Fees'), ('licence', 'Invoice line for Licence Fees')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activityinvoiceline',
            name='invoice_reference',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activityinvoiceline',
            name='licence_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.LicencePurpose'),
        ),
    ]
