# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-18 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0503_auto_20200818_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityinvoiceline',
            name='invoice_datetime',
        ),
        migrations.RemoveField(
            model_name='activityinvoiceline',
            name='invoice_reference',
        ),
    ]
