# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-18 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0505_applicationselectedactivitypurpose_property_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenceactivity',
            name='oracle_account_code',
        ),
        migrations.AddField(
            model_name='licencepurpose',
            name='oracle_account_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
