# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-24 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0506_auto_20200818_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencepurpose',
            name='not_renewable',
            field=models.BooleanField(default=False, help_text='If ticked, the licenced Purpose can not be renewed.'),
        ),
    ]
