# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-26 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0507_licencepurpose_not_renewable'),
        ('wildlifecompliance', '0508_auto_20200826_1445'),
    ]

    operations = [
    ]
