# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-25 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0509_return_property_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationselectedactivity',
            name='additional_fee',
        ),
        migrations.RemoveField(
            model_name='applicationselectedactivity',
            name='additional_fee_text',
        ),
    ]
