# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-26 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0509_merge_20200826_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purposespecies',
            name='purpose',
        ),
        migrations.AddField(
            model_name='purposespecies',
            name='licence_purpose',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purpose_species', to='wildlifecompliance.LicencePurpose'),
            preserve_default=False,
        ),
    ]
