# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-26 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0510_auto_20200826_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='purposespecies',
            name='species',
            field=models.NullBooleanField(),
        ),
    ]
