# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-31 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0513_auto_20200830_2103'),
        ('wildlifecompliance', '0511_purposespecies_species'),
    ]

    operations = [
    ]
