# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-15 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0515_returntyperegulatedspecies'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstandardcondition',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
