# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-18 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0517_auto_20200918_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='purposespecies',
            name='species',
            field=models.NullBooleanField(),
        ),
    ]
