# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0518_purposespecies_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returntable',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
