# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-25 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0519_auto_20200922_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnactivity',
            name='activity_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('in_import', 'In through acquisition'), ('in_birth', 'In through birth'), ('in_transfer', 'In through transfer'), ('out_death', 'Out through death'), ('out_export', 'Out through disposal')], default='stock', max_length=20),
        ),
    ]
