# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-30 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0520_auto_20200925_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_resubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
