# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-01 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0521_application_is_resubmitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencepurpose',
            name='regulation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
