# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-13 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0524_systemmaintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_resubmitted',
        ),
    ]
