# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-24 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0525_remove_application_is_resubmitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencepurpose',
            name='minimum_age',
            field=models.SmallIntegerField(default=18),
        ),
    ]
