# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-12-10 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0526_licencepurpose_minimum_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penaltyamount',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='penaltyamount',
            name='amount_after_due',
        ),
        migrations.RemoveField(
            model_name='sanctionoutcome',
            name='penalty_amount_1st',
        ),
        migrations.RemoveField(
            model_name='sanctionoutcome',
            name='penalty_amount_2nd',
        ),
        migrations.AlterField(
            model_name='actiontakendocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artifactcommslogdocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artifactdocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='briefofevidencedocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='callemaildocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='callemaillogdocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='courthearingnoticedocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inspectioncommslogdocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inspectiondocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inspectionreportdocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inspectiontypeapprovaldocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='issuancedocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='legalcasecommslogdocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='legalcasedocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='legalcasegenerateddocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='offence',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('pending_closure', 'Pending Closure'), ('closed', 'Closed'), ('discarded', 'Discarded')], default='open', max_length=40),
        ),
        migrations.AlterField(
            model_name='offencecommslogdocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='prosecutionbriefdocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='prosecutionnoticedocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='remediationaction',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('overdue', 'Overdue'), ('submitted', 'Submitted'), ('accepted', 'Accepted')], max_length=40),
        ),
        migrations.AlterField(
            model_name='rendererdocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sanctionoutcome',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('over_paid', 'Over Paid')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sanctionoutcome',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_endorsement', 'Awaiting Endorsement'), ('awaiting_payment', 'Awaiting Payment'), ('with_dot', 'With Dep. of Transport'), ('awaiting_issuance', 'Awaiting Issuance'), ('awaiting_review', 'Awaiting Review'), ('awaiting_issuance', 'Awaiting Issuance'), ('awaiting_remediation_actions', 'Awaiting Remediation Actions'), ('escalated_for_withdrawal', 'Escalated for Withdrawal'), ('declined', 'Declined'), ('overdue', 'Overdue'), ('withdrawn', 'Withdrawn'), ('closed', 'Closed')], default='draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='sanctionoutcome',
            name='type',
            field=models.CharField(blank=True, choices=[('infringement_notice', 'Infringement Notice'), ('caution_notice', 'Caution Notice'), ('letter_of_advice', 'Letter of Advice'), ('remediation_notice', 'Remediation Notice')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sanctionoutcomecommslogdocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sanctionoutcomeduedate',
            name='due_date_term_currently_applied',
            field=models.CharField(default='1st', max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionregulation',
            name='dotag_offence_code',
            field=models.CharField(blank=True, max_length=9, verbose_name='DotAG Offence Code'),
        ),
        migrations.AlterField(
            model_name='sectionregulation',
            name='issue_due_date_window',
            field=models.PositiveSmallIntegerField(blank=True, help_text='An infringement notice must be issued within Issue-due-date-window days from the date of the offence occurred.', null=True),
        ),
        migrations.AlterField(
            model_name='sectionregulation',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Regulation'),
        ),
        migrations.AlterField(
            model_name='temporarydocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
