# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-18 08:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0528_auto_20201210_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstandardcondition',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
