# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-18 09:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0529_auto_20210118_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstandardcondition',
            name='additional_information',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
