# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 02:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0530_auto_20210118_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purposespecies',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
