# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-23 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0531_auto_20210120_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='processing_status',
            field=models.CharField(choices=[('due', 'Due'), ('overdue', 'Overdue'), ('draft', 'Draft'), ('future', 'Future'), ('with_curator', 'With Curator'), ('accepted', 'Accepted'), ('payment', 'Awaiting Payment'), ('discarded', 'Discarded')], default='future', max_length=20),
        ),
    ]
