# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-17 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0531_auto_20210120_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'CM_Act',
                'verbose_name_plural': 'CM_Acts',
            },
        ),
        migrations.AlterField(
            model_name='sectionregulation',
            name='act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_regulations', to='wildlifecompliance.Act'),
        ),
    ]
