# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0532_auto_20210323_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencepurpose',
            name='version',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='licencepurpose',
            unique_together=set([('name', 'version')]),
        ),
    ]
