# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-17 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0533_auto_20210217_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='acronym',
            field=models.CharField(choices=[('BCA', 'Biodiversity something'), ('CALM', 'Conservation and Land Management Act')], max_length=50),
        ),
    ]
