# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-17 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0534_auto_20210217_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='acronym',
        ),
        migrations.AlterField(
            model_name='act',
            name='name',
            field=models.CharField(choices=[('BCA', 'Biodiversity Conservation Act 2016'), ('CALM', 'Conservation and Land Management Act 1984')], max_length=50),
        ),
    ]
