# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-18 03:30
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0536_auto_20210515_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionquestion',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('isRepeatable', 'isRepeatable'), ('isRequired', 'isRequired'), ('isLicenceField', 'isRequired - Licence Field'), ('PromptInspection', 'isRequired - Inspection')], max_length=400, null=True),
        ),
    ]
