# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-05 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0537_auto_20210223_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionoutcome',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_endorsement', 'Awaiting Endorsement'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_print_and_post', 'Awaiting Print and Post'), ('with_dot', 'With Dep. of Transport'), ('awaiting_issuance', 'Awaiting Issuance'), ('awaiting_review', 'Awaiting Review'), ('awaiting_issuance', 'Awaiting Issuance'), ('awaiting_remediation_actions', 'Awaiting Remediation Actions'), ('escalated_for_withdrawal', 'Escalated for Withdrawal'), ('declined', 'Declined'), ('overdue', 'Overdue'), ('withdrawn', 'Withdrawn'), ('closed', 'Closed')], default='draft', max_length=40),
        ),
    ]
