# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-02 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0538_auto_20210524_1005'),
        ('wildlifecompliance', '0539_auto_20210317_1151'),
    ]

    operations = [
    ]
