# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-10 05:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0541_auto_20210609_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiongroup',
            name='property_cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
