# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-17 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0542_sectiongroup_property_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstandardcondition',
            name='additional_information',
        ),
    ]
