# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-29 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0540_merge_20210602_1541'),
        ('wildlifecompliance', '0544_auto_20210624_1653'),
    ]

    operations = [
    ]
