# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-29 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0545_merge_20211029_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanctionoutcomeduedateconfiguration',
            options={'ordering': ('date_of_enforcement',), 'verbose_name': 'CM_Sanction Outcome Due Date Configuration', 'verbose_name_plural': 'CM_Sanction Outcome Due Date Configuration'},
        ),
        migrations.AlterField(
            model_name='act',
            name='name',
            field=models.CharField(choices=[('BCA', 'Biodiversity Conservation Act 2016'), ('CALM', 'Conservation and Land Management Act 1984'), ('BCR', 'Biodiversity Conservation Regulations 2018'), ('CLMR', 'Conservation and Land Management Regulations 2002'), ('FMR', 'Forest Management Regulations 1993'), ('CIIPA', 'Criminal Investigation (Identifying People) Act 2006'), ('SCMRA', 'Swan and Canning Rivers Management Act 2006'), ('SCRMR', 'Swan and Canning Rivers Management Regulations 2007')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sanctionoutcomewordtemplate',
            name='act',
            field=models.CharField(blank=True, choices=[('BCA', 'Biodiversity Conservation Act 2016'), ('CALM', 'Conservation and Land Management Act 1984'), ('BCR', 'Biodiversity Conservation Regulations 2018'), ('CLMR', 'Conservation and Land Management Regulations 2002'), ('FMR', 'Forest Management Regulations 1993'), ('CIIPA', 'Criminal Investigation (Identifying People) Act 2006'), ('SCMRA', 'Swan and Canning Rivers Management Act 2006'), ('SCRMR', 'Swan and Canning Rivers Management Regulations 2007')], max_length=30),
        ),
    ]
