# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-16 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0546_auto_20211029_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentartifact',
            name='officer_interviewer_email',
        ),
        migrations.RemoveField(
            model_name='physicalartifact',
            name='custodian_email',
        ),
        migrations.RemoveField(
            model_name='physicalartifact',
            name='officer_email',
        ),
        migrations.AddField(
            model_name='physicalartifact',
            name='custodian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_artifact_custodian', to=settings.AUTH_USER_MODEL),
        ),
    ]
