# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-15 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0546_auto_20211029_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('general_enquiry', 'General Enquiry'), ('illegal_activity', 'Illegal Activity'), ('amphibian', 'Ambhibian - e.g. frog, cane toad'), ('mammal', 'Mammal'), ('bird', 'Bird')], default='amphibian', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'CM_CallType',
                'verbose_name_plural': 'CM_CallTypes',
            },
        ),
    ]
