# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-15 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wildlifecompliance.components.offence.models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0546_auto_20211029_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffenceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=255, upload_to=wildlifecompliance.components.offence.models.update_offence_doc_filename)),
                ('sanction_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='wildlifecompliance.Offence')),
            ],
            options={
                'verbose_name': 'CM_SanctionOutcomeDocument',
                'verbose_name_plural': 'CM_SanctionOutcomeDocuments',
            },
        ),
    ]
