# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-16 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0547_calltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='call_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_type', to='wildlifecompliance.CallType'),
        ),
    ]
