# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-15 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0547_offencedocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offencedocument',
            options={'verbose_name': 'CM_OffenceDocument', 'verbose_name_plural': 'CM_OffenceDocuments'},
        ),
        migrations.RenameField(
            model_name='offencedocument',
            old_name='sanction_outcome',
            new_name='offence',
        ),
    ]
