# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-22 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0547_auto_20211116_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceUserIntelligenceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=255, upload_to='')),
                ('email_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationIntelligenceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=255, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='compliancemanagementuserpreferences',
            name='intelligence_information_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='intelligence_information_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisationintelligencedocument',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_documents', to='wildlifecompliance.Organisation'),
        ),
    ]
