# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-17 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0548_callemail_call_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='dead',
            field=models.BooleanField(default=False),
        ),
    ]
