# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-22 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0548_auto_20211122_1506'),
        ('wildlifecompliance', '0548_auto_20211115_1106'),
    ]

    operations = [
    ]
