# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-17 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0549_callemail_dead'),
        ('wildlifecompliance', '0547_auto_20211116_1438'),
    ]

    operations = [
    ]
