# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-18 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0550_merge_20211117_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='euthanise',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calltype',
            name='name',
            field=models.CharField(choices=[('general_enquiry', 'General Enquiry'), ('illegal_activity', 'Illegal Activity'), ('amphibian', 'Ambhibian - e.g. frog, cane toad'), ('mammal', 'Mammal'), ('bird', 'Bird'), ('non_native_species', 'Non native species - e.g. pigeon, fox, cattle, peacock'), ('reptile', 'Reptile - e.g. snake, turtles, lizard'), ('other', 'Other - e.g. spider, bees, fish')], default='amphibian', max_length=50, unique=True),
        ),
    ]
