# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-19 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0552_callemail_number_of_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='brief_nature_of_call',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
