# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0555_auto_20211123_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='entangled_other',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
