# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0556_callemail_entangled_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callemail',
            name='entangled_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
