# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 06:58
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0557_auto_20211124_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('unknown', 'UnKnown')], max_length=30, null=True),
        ),
    ]
