# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 07:37
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0558_callemail_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='age',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('baby', 'Baby'), ('adult', 'Adult'), ('juvenile', 'Juvenile')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='callemail',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('unknown', 'Unknown')], max_length=30, null=True),
        ),
    ]
