# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-25 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0560_callemail_baby_kangaroo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildcareSpeciesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cane_toad', 'Cane Toad'), ('frog', 'Frog'), ('coot', 'Coot'), ('goose', 'Goose'), ('snake', 'Snake')], max_length=100, unique=True)),
                ('call_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.CallType')),
            ],
            options={
                'verbose_name': 'CM_WilcareSpeciesType',
                'verbose_name_plural': 'CM_WilcareSpeciesTypes',
                'ordering': ['name'],
            },
        ),
    ]
