# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-25 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0561_wildcarespeciestype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildcarespeciestype',
            name='name',
            field=models.CharField(choices=[('cane_toad', 'Cane Toad'), ('frog', 'Frog'), ('coot', 'Coot'), ('goose', 'Goose'), ('snake', 'Snake')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='wildcarespeciestype',
            unique_together=set([('name', 'call_type')]),
        ),
    ]
