# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-25 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0563_auto_20211125_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wildcarespeciestype',
            options={'ordering': ['name'], 'verbose_name': 'CM_WildcareSpeciesType', 'verbose_name_plural': 'CM_WildcareSpeciesTypes'},
        ),
        migrations.AlterField(
            model_name='wildcarespeciestype',
            name='call_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildcare_species_types', to='wildlifecompliance.CallType'),
        ),
    ]
