# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-25 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0565_auto_20211125_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wildcarespeciestype',
            options={'ordering': ['species_name'], 'verbose_name': 'CM_WildcareSpeciesType', 'verbose_name_plural': 'CM_WildcareSpeciesTypes'},
        ),
        migrations.RenameField(
            model_name='wildcarespeciestype',
            old_name='name',
            new_name='species_name',
        ),
        migrations.AlterUniqueTogether(
            name='wildcarespeciestype',
            unique_together=set([('species_name', 'call_type')]),
        ),
    ]
