# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-26 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0567_auto_20211126_1010'),
        ('wildlifecompliance', '0549_merge_20211122_1651'),
    ]

    operations = [
    ]
