# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-26 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0569_callemail_wildcare_species_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildcareSpeciesSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_sub_name', models.CharField(choices=[('corella', 'Corella'), ('red_tailed_black', 'Red-tailed Black'), ('kestrel', 'Kestrel')], max_length=100)),
                ('wildcare_species_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildcare_species_sub_types', to='wildlifecompliance.WildcareSpeciesType')),
            ],
            options={
                'verbose_name': 'CM_WildcareSpeciesSubType',
                'verbose_name_plural': 'CM_WildcareSpeciesSubTypes',
                'ordering': ['species_sub_name'],
            },
        ),
        migrations.AddField(
            model_name='callemail',
            name='wildcare_species_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildcare_species_sub_type', to='wildlifecompliance.WildcareSpeciesSubType'),
        ),
        migrations.AlterUniqueTogether(
            name='wildcarespeciessubtype',
            unique_together=set([('species_sub_name', 'wildcare_species_type')]),
        ),
    ]
