# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-26 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0570_auto_20211126_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ben_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
