# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-29 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0571_location_ben_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='species_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
