# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-30 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0575_auto_20211129_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildcarespeciessubtype',
            name='species_sub_name',
            field=models.CharField(choices=[('corella', 'Corella'), ('red_tailed_black', 'Red-tailed Black'), ('white_tailed_black', 'White-tailed Black'), ('swamphen', 'Swamphen'), ('darter', 'Darter'), ('goshawk', 'Goshawk'), ('osprey', 'osprey'), ('kestrel', 'Kestrel'), ('peregrine', 'Peregrine'), ('wedge_tailed', 'Wedge-tailed'), ('white_bellied_sea', 'White-bellied Sea'), ('egret', 'Egret'), ('nankeen_night', 'Nankeen Night'), ('new_holland', 'New Holland'), ('wattlebird', 'Wattlebird'), ('blue_winged_kookaburra', 'Blue-winged Kookaburra'), ('laughing_kookaburra', 'Laughing Kookaburra'), ('sacred', 'Sacred'), ('barn', 'Barn'), ('bookbook', 'Bookbook'), ('28_australian_ringneck', '28 - Australian Ringneck'), ('cockatiel', 'Cockatiel'), ('galah_pink_and_grey', 'Galah - Pink and Grey'), ('rosella', 'Rosella'), ('little', 'Little'), ('welcome', 'Welcome'), ('tammar_wallaby', 'Tammar-Wallaby'), ('western_grey', 'Western Grey'), ('brushtail', 'Brushtail'), ('pygmy', 'Pygmy'), ('ringtail', 'Ringtail'), ('blue_tongue_bobtail', 'Blue Tongue, Bobtail'), ('goanna', 'Goanna'), ('monitor', 'Monitor'), ('skink', 'Skink'), ('dugite', 'Dugite'), ('python', 'Python'), ('tiger', 'Tiger'), ('long_necked_oblanga', 'Long-necked (oblanga)'), ('marine', 'Marine'), ('western_swamp', 'Western Swamp')], max_length=100),
        ),
        migrations.AlterField(
            model_name='wildcarespeciestype',
            name='species_name',
            field=models.CharField(choices=[('cane_toad', 'Cane Toad'), ('frog', 'Frog'), ('butcherbird', 'Butcherbird'), ('cockatoo', 'Cockatoo'), ('coot', 'Coot'), ('cormorant', 'Cormorant'), ('duck', 'Duck'), ('eagle_falcon_hawk', 'Eagle, Falcon, Hawk'), ('emu', 'Emu'), ('goose', 'Goose'), ('heron', 'Heron'), ('honeyeater', 'Honeyeater'), ('ibis', 'Ibis'), ('kingfisher', 'Kingfisher'), ('magpie', 'Magpie'), ('magpie_lark', 'Magpie-Lark'), ('owl', 'Owl'), ('parrot', 'Parrot'), ('peacock', 'Peacock'), ('penguin', 'Penguin'), ('quail', 'Quail'), ('rainbow_bee_eater', 'Rainbow Bee-Eater'), ('rainbow_lorikeet', 'Rainbow Lorikeet'), ('raven', 'Raven'), ('albatross', 'Albatross'), ('gull', 'Gull'), ('pelican', 'Pelican'), ('shearwater', 'Shearwater'), ('tern', 'Tern'), ('swallow', 'Swallow'), ('swan', 'Swan'), ('tawny_frogmouth', 'Tawny Frogmouth'), ('willy_wagtail', 'Willy Wagtail'), ('bat', 'Bat'), ('dingo', 'Dingo'), ('dolphin', 'Dolphin'), ('echidna', 'Echidna'), ('ferret', 'Ferret'), ('kangaroo', 'Kangaroo'), ('possum', 'Possum'), ('quenda_or_bandicoot', 'Quenda or Bandicoot'), ('quokka', 'Quokka'), ('seal_and_sealion', 'Seal and Sea Lion'), ('whale', 'Whale'), ('wombat', 'Wombat'), ('lizard', 'Lizard'), ('snake', 'Snake'), ('turtle', 'Turtle'), ('cat', 'Cat'), ('dog', 'Dog'), ('fox', 'Fox'), ('rabbit', 'Rabbit'), ('rodent', 'Rodent - Rat, mouse'), ('chicken', 'Chicken'), ('duck_domestic', 'Duck - domestic'), ('indian_ringneck_parakeet', 'Indian Ringneck Parakeet'), ('pigeon_or_dove', 'Pigeon or Dove'), ('fish', 'Fish'), ('shark', 'Shark'), ('caterpillar', 'Caterpillar'), ('bees_and_wasps', 'Bees And Wasps'), ('crab', 'Crab'), ('spider', 'Spider'), ('other', 'Other')], max_length=100),
        ),
    ]
