# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-20 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0577_auto_20211201_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callemail',
            name='dead',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='callemail',
            name='euthanise',
            field=models.BooleanField(),
        ),
    ]
