# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-20 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0578_auto_20211220_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callemail',
            name='dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='callemail',
            name='euthanise',
            field=models.BooleanField(default=False),
        ),
    ]
