# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-21 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0581_auto_20211221_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildcarespeciestype',
            name='call_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildcare_species_types', to='wildlifecompliance.CallType'),
        ),
        migrations.AlterField(
            model_name='wildcarespeciestype',
            name='species_name',
            field=models.CharField(choices=[('cane_toad', 'Cane Toad'), ('frog', 'Frog'), ('butcherbird', 'Butcherbird'), ('cockatoo', 'Cockatoo'), ('coot', 'Coot'), ('cormorant', 'Cormorant'), ('duck', 'Duck'), ('eagle_falcon_hawk', 'Eagle, Falcon, Hawk'), ('emu', 'Emu'), ('goose', 'Goose'), ('heron', 'Heron'), ('honeyeater', 'Honeyeater'), ('ibis', 'Ibis'), ('kingfisher', 'Kingfisher'), ('magpie', 'Magpie'), ('magpie_lark', 'Magpie-Lark'), ('owl', 'Owl'), ('parrot', 'Parrot'), ('peacock', 'Peacock'), ('penguin', 'Penguin'), ('quail', 'Quail'), ('rainbow_bee_eater', 'Rainbow Bee-Eater'), ('rainbow_lorikeet', 'Rainbow Lorikeet'), ('raven', 'Raven'), ('albatross', 'Albatross'), ('gull', 'Gull'), ('pelican', 'Pelican'), ('shearwater', 'Shearwater'), ('tern', 'Tern'), ('swallow', 'Swallow'), ('swan', 'Swan'), ('tawny_frogmouth', 'Tawny Frogmouth'), ('willy_wagtail', 'Willy Wagtail'), ('bat', 'Bat'), ('dingo', 'Dingo'), ('dolphin', 'Dolphin'), ('echidna', 'Echidna'), ('ferret', 'Ferret'), ('kangaroo', 'Kangaroo'), ('possum', 'Possum'), ('quenda_or_bandicoot', 'Quenda or Bandicoot'), ('quokka', 'Quokka'), ('seal_and_sealion', 'Seal and Sea Lion'), ('whale', 'Whale'), ('wombat', 'Wombat'), ('lizard', 'Lizard'), ('snake', 'Snake'), ('turtle', 'Turtle'), ('cat', 'Cat'), ('dog', 'Dog'), ('fox', 'Fox'), ('rabbit', 'Rabbit'), ('rodent', 'Rodent - Rat, mouse'), ('chicken', 'Chicken'), ('duck_domestic', 'Duck - domestic'), ('indian_ringneck_parakeet', 'Indian Ringneck Parakeet'), ('pigeon_or_dove', 'Pigeon or Dove'), ('fish', 'Fish'), ('shark', 'Shark'), ('caterpillar', 'Caterpillar'), ('bees_and_wasps', 'Bees And Wasps'), ('crab', 'Crab'), ('spider', 'Spider'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
