# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-22 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0583_auto_20211221_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildcarespeciestype',
            name='call_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wildcare_species_types', to='wildlifecompliance.CallType'),
            preserve_default=False,
        ),
    ]
