# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-13 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0586_auto_20211231_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltype',
            name='all_wildcare_species',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calltype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
