# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-14 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0587_auto_20220214_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildcarespeciestype',
            name='species_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
