# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-17 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0590_auto_20220217_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calltype',
            old_name='index',
            new_name='call_type_index',
        ),
    ]
