# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-17 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0591_auto_20220217_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildcarespeciestype',
            name='show_species_name_textbox',
            field=models.BooleanField(default=False),
        ),
    ]
