# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-17 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0592_wildcarespeciestype_show_species_name_textbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wildcarespeciestype',
            old_name='check_pinky_joe',
            new_name='check_pinky_joey',
        ),
    ]
