# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-23 09:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0593_auto_20220217_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictGIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkb_geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('district_name', models.CharField(blank=True, max_length=200, null=True)),
                ('office', models.CharField(blank=True, max_length=200, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['object_id'],
            },
        ),
        migrations.CreateModel(
            name='RegionGIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkb_geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('region_name', models.CharField(blank=True, max_length=200, null=True)),
                ('office', models.CharField(blank=True, max_length=200, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['object_id'],
            },
        ),
    ]
