# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-25 09:12
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0595_auto_20220525_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiondistrict',
            name='region',
        ),
        migrations.AlterModelManagers(
            name='compliancepermissiongroup',
            managers=[
                ('district_groups', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='callemail',
            name='district',
        ),
        migrations.RemoveField(
            model_name='callemail',
            name='region',
        ),
        migrations.RemoveField(
            model_name='compliancepermissiongroup',
            name='region_district',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='district',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='region',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='district',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='region',
        ),
        migrations.RemoveField(
            model_name='offence',
            name='district',
        ),
        migrations.RemoveField(
            model_name='offence',
            name='region',
        ),
        migrations.RemoveField(
            model_name='sanctionoutcome',
            name='district',
        ),
        migrations.RemoveField(
            model_name='sanctionoutcome',
            name='region',
        ),
        migrations.AddField(
            model_name='compliancepermissiongroup',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.District'),
        ),
        migrations.AddField(
            model_name='compliancepermissiongroup',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.Region'),
        ),
        migrations.DeleteModel(
            name='RegionDistrict',
        ),
    ]
