# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-26 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0596_auto_20220525_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name'], 'verbose_name': 'CM_District', 'verbose_name_plural': 'CM_Districts'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'CM_Region', 'verbose_name_plural': 'CM_Regions'},
        ),
    ]
