# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-27 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0597_auto_20220526_0827'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='compliancepermissiongroup',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='head_office',
            field=models.BooleanField(default=False),
        ),
    ]
