# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-30 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0598_auto_20220527_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='cddp_name',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='cddp_name',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
