# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-31 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0599_auto_20220530_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='head_office',
        ),
    ]
