# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-01 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0601_auto_20220601_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallEmailTriageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.District')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.Region')),
            ],
            options={
                'verbose_name': 'CM_CallEmailTriageGroup',
                'verbose_name_plural': 'CM_CallEmail_Triage_Groups',
            },
        ),
        migrations.CreateModel(
            name='ManagerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.District')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.Region')),
            ],
            options={
                'verbose_name': 'CM_ManagerGroup',
                'verbose_name_plural': 'CM_Manager_Groups',
            },
        ),
        migrations.CreateModel(
            name='OfficerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.District')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.Region')),
            ],
            options={
                'verbose_name': 'CM_OfficerGroup',
                'verbose_name_plural': 'CM_Officer_Groups',
            },
        ),
        migrations.CreateModel(
            name='VolunteerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.District')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.Region')),
            ],
            options={
                'verbose_name': 'CM_Volunteer',
                'verbose_name_plural': 'CM_Volunteers',
            },
        ),
    ]
