# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-01 07:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0603_auto_20220601_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callemailtriagegroup',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.District'),
        ),
        migrations.AlterField(
            model_name='managergroup',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.District'),
        ),
        migrations.AlterField(
            model_name='officergroup',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.District'),
        ),
        migrations.AlterField(
            model_name='volunteergroup',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.District'),
        ),
    ]
