# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-02 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0605_auto_20220602_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteergroup',
            name='district',
        ),
        migrations.RemoveField(
            model_name='volunteergroup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='volunteergroup',
            name='region',
        ),
    ]
