# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-03 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0606_auto_20220602_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complianceadmingroup',
            options={'verbose_name': 'CM Compliance Admin Group', 'verbose_name_plural': 'CM Compliance Admin Group'},
        ),
        migrations.AlterModelOptions(
            name='compliancemanagementapprovedexternalusergroup',
            options={'verbose_name': 'CM Compliance Management Approved External User Group', 'verbose_name_plural': 'CM Compliance Management Approved External User Group'},
        ),
        migrations.AlterModelOptions(
            name='compliancemanagementcallemailreadonlygroup',
            options={'verbose_name': 'CM Compliance Management Call Email Read Only Group', 'verbose_name_plural': 'CM Compliance Management Call Email Read Only Group'},
        ),
        migrations.AlterModelOptions(
            name='compliancemanagementreadonlygroup',
            options={'verbose_name': 'CM Compliance Management Read Only Group', 'verbose_name_plural': 'CM Compliance Management Read Only Group'},
        ),
        migrations.AlterModelOptions(
            name='infringementnoticecoordinatorgroup',
            options={'verbose_name': 'CM_InfringementNoticeCoordinatorGroup', 'verbose_name_plural': 'CM Infringement Notice Coordinator Group'},
        ),
        migrations.AlterModelOptions(
            name='licensingadmingroup',
            options={'verbose_name': 'CM Licensing Admin Group', 'verbose_name_plural': 'CM Licensing Admin Group'},
        ),
        migrations.AlterModelOptions(
            name='prosecutioncoordinatorgroup',
            options={'verbose_name': 'CM_ProsecutionCoordinatorGroup', 'verbose_name_plural': 'CM Prosecution Coordinator Group'},
        ),
        migrations.AlterModelOptions(
            name='prosecutioncouncilgroup',
            options={'verbose_name': 'CM Prosecution Council Group', 'verbose_name_plural': 'CM Prosecution Council Group'},
        ),
        migrations.AlterModelOptions(
            name='prosecutionmanagergroup',
            options={'verbose_name': 'CM Prosecution Manager Group', 'verbose_name_plural': 'CM Prosecution Manager Group'},
        ),
        migrations.AlterModelOptions(
            name='volunteergroup',
            options={'verbose_name': 'CM Volunteer Group', 'verbose_name_plural': 'CM Volunteer Group'},
        ),
        migrations.AddField(
            model_name='region',
            name='head_office',
            field=models.BooleanField(default=False),
        ),
    ]
