# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-13 03:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0607_auto_20220603_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'External User Group',
                'verbose_name_plural': 'External User Groups',
            },
        ),
        migrations.CreateModel(
            name='ExternalUserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('emailuser', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('external_user_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.ExternalUserGroup')),
            ],
        ),
        migrations.AlterModelOptions(
            name='managergroup',
            options={'verbose_name': 'CM_ManagerGroup', 'verbose_name_plural': 'CM Manager Groups'},
        ),
    ]
