# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-13 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0608_auto_20220613_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externaluserpermission',
            name='emailuser',
        ),
        migrations.RemoveField(
            model_name='externaluserpermission',
            name='external_user_group',
        ),
        migrations.AlterField(
            model_name='compliancemanagementapprovedexternalusergroup',
            name='members',
            field=models.ManyToManyField(related_name='approved_external_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ExternalUserGroup',
        ),
        migrations.DeleteModel(
            name='ExternalUserPermission',
        ),
    ]
