# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-13 08:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0609_auto_20220613_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancemanagementapprovedexternalusergroup',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
