# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-14 06:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0610_auto_20220613_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceManagementSystemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Compliance Management System Group',
                'verbose_name_plural': 'ComplianceManagement System Groups',
            },
        ),
        migrations.CreateModel(
            name='ComplianceManagementSystemGroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('compliance_management_system_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.ComplianceManagementSystemGroup')),
                ('emailuser', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
