# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-14 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0612_compliancemanagementsystemgroup_can_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancemanagementsystemgroup',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.District'),
        ),
        migrations.AddField(
            model_name='compliancemanagementsystemgroup',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.Region'),
        ),
        migrations.AlterField(
            model_name='compliancemanagementsystemgroup',
            name='name',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('infringement_notice_coordinator', 'Infringement Notice Coordinator'), ('prosecution_notice_coordinator', 'Prosecution Notice Coordinator'), ('prosecution_manager', 'Prosecution Manager'), ('prosecution_council', 'Prosecution Council'), ('compliance_management_read_only', 'Compliance Management Read Only'), ('compliance_management_call_email_read_only', 'Compliance Management Call Email Read Only'), ('compliance_management_approved_external_users', 'Compliance Management Approved External Users'), ('compliance_admin', 'Compliance Admin')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='compliancemanagementsystemgroup',
            unique_together=set([('name', 'region', 'district')]),
        ),
    ]
