# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-14 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0613_auto_20220614_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancemanagementsystemgroup',
            name='name',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('infringement_notice_coordinator', 'Infringement Notice Coordinator'), ('prosecution_coordinator', 'Prosecution Notice Coordinator'), ('prosecution_manager', 'Prosecution Manager'), ('prosecution_council', 'Prosecution Council'), ('compliance_management_read_only', 'Compliance Management Read Only'), ('compliance_management_call_email_read_only', 'Compliance Management Call Email Read Only'), ('compliance_management_approved_external_user', 'Compliance Management Approved External User'), ('compliance_admin', 'Compliance Admin'), ('licensing_admin', 'Licensing Admin')], max_length=200),
        ),
    ]
