# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-14 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0614_auto_20220614_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callemailtriagegroup',
            name='district',
        ),
        migrations.RemoveField(
            model_name='callemailtriagegroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='callemailtriagegroup',
            name='region',
        ),
        migrations.RemoveField(
            model_name='complianceadmingroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='compliancemanagementapprovedexternalusergroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='compliancemanagementcallemailreadonlygroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='compliancemanagementreadonlygroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='infringementnoticecoordinatorgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='licensingadmingroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='managergroup',
            name='district',
        ),
        migrations.RemoveField(
            model_name='managergroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='managergroup',
            name='region',
        ),
        migrations.RemoveField(
            model_name='officergroup',
            name='district',
        ),
        migrations.RemoveField(
            model_name='officergroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='officergroup',
            name='region',
        ),
        migrations.RemoveField(
            model_name='prosecutioncoordinatorgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='prosecutioncouncilgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='prosecutionmanagergroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='volunteergroup',
            name='members',
        ),
        migrations.AlterModelOptions(
            name='compliancemanagementsystemgroup',
            options={'verbose_name': 'CM_Compliance Management System Group', 'verbose_name_plural': 'CM_Compliance Management System Groups'},
        ),
        migrations.RemoveField(
            model_name='compliancemanagementsystemgroup',
            name='can_delete',
        ),
        migrations.AlterField(
            model_name='compliancemanagementsystemgroup',
            name='name',
            field=models.CharField(choices=[('call_email_triage', 'Call Email Triage'), ('officer', 'Officer'), ('manager', 'Manager'), ('volunteer', 'Volunteer'), ('infringement_notice_coordinator', 'Infringement Notice Coordinator'), ('prosecution_coordinator', 'Prosecution Notice Coordinator'), ('prosecution_manager', 'Prosecution Manager'), ('prosecution_council', 'Prosecution Council'), ('compliance_management_read_only', 'Compliance Management Read Only'), ('compliance_management_call_email_read_only', 'Compliance Management Call Email Read Only'), ('compliance_management_approved_external_user', 'Compliance Management Approved External User'), ('compliance_admin', 'Compliance Admin'), ('licensing_admin', 'Licensing Admin')], max_length=200),
        ),
        migrations.DeleteModel(
            name='CallEmailTriageGroup',
        ),
        migrations.DeleteModel(
            name='ComplianceAdminGroup',
        ),
        migrations.DeleteModel(
            name='ComplianceManagementApprovedExternalUserGroup',
        ),
        migrations.DeleteModel(
            name='ComplianceManagementCallEmailReadOnlyGroup',
        ),
        migrations.DeleteModel(
            name='ComplianceManagementReadOnlyGroup',
        ),
        migrations.DeleteModel(
            name='InfringementNoticeCoordinatorGroup',
        ),
        migrations.DeleteModel(
            name='LicensingAdminGroup',
        ),
        migrations.DeleteModel(
            name='ManagerGroup',
        ),
        migrations.DeleteModel(
            name='OfficerGroup',
        ),
        migrations.DeleteModel(
            name='ProsecutionCoordinatorGroup',
        ),
        migrations.DeleteModel(
            name='ProsecutionCouncilGroup',
        ),
        migrations.DeleteModel(
            name='ProsecutionManagerGroup',
        ),
        migrations.DeleteModel(
            name='VolunteerGroup',
        ),
    ]
