# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-14 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0616_auto_20220614_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='allocated_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.ComplianceManagementSystemGroup'),
        ),
    ]
