# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-14 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_compliancemanagementsystemgroup_compliancemanagementsystemgrouppermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancemanagementsystemgrouppermission',
            name='compliance_management_system_group',
        ),
        migrations.RemoveField(
            model_name='compliancemanagementsystemgrouppermission',
            name='emailuser',
        ),
        migrations.DeleteModel(
            name='ComplianceManagementSystemGroup',
        ),
        migrations.DeleteModel(
            name='ComplianceManagementSystemGroupPermission',
        ),
    ]
